[package]
name = "smeazy-mpesa"
version = "0.1.0"
edition = "2021"

[dependencies]
serde         = { workspace = true }
serde_json    = { workspace = true }
uuid          = { workspace = true }
chrono        = { workspace = true }
rust_decimal  = { workspace = true }
thiserror     = { workspace = true }
tracing       = { workspace = true }
sqlx          = { workspace = true }
axum          = { workspace = true }
reqwest       = { workspace = true }
hex           = { workspace = true }
ring          = { workspace = true }
tokio         = { workspace = true }
smeazy-domain = { workspace = true }
smeazy-common = { workspace = true }
