[package]
name = "smeazy-iam"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
sqlx = { workspace = true }
axum = { workspace = true }
jsonwebtoken = { workspace = true }
argon2 = { workspace = true }
rand   = { workspace = true }
ring   = { workspace = true }
smeazy-domain = { workspace = true }
smeazy-common = { workspace = true }
